import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { run } from './common.ts';

const scriptsDir = path.dirname(fileURLToPath(import.meta.url));
const ARTIFACTS_DIR = path.resolve(scriptsDir, '../artifacts/contracts');
const OUTPUT_DIR = path.resolve(scriptsDir, '../../src/config/abis');

const BANNER =
  '// Generated by contracts/scripts/sync-abis.ts — run `npm run sync-abis` after changing a contract.';

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Serialises the ABI as a TypeScript literal in the repo's Prettier style
 * (single quotes, bare keys, trailing commas) so the generated files survive
 * `npm run format:check` without anyone having to reformat them by hand.
 */
function toLiteral(value: unknown, depth: number): string {
  const pad = '  '.repeat(depth);
  const inner = '  '.repeat(depth + 1);

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    return `[\n${value.map((item) => `${inner}${toLiteral(item, depth + 1)},`).join('\n')}\n${pad}]`;
  }
  if (typeof value === 'object' && value !== null) {
    const entries = Object.entries(value);
    if (entries.length === 0) return '{}';
    const body = entries
      .map(
        ([key, item]) =>
          `${inner}${IDENTIFIER.test(key) ? key : quote(key)}: ${toLiteral(item, depth + 1)},`,
      )
      .join('\n');
    return `{\n${body}\n${pad}}`;
  }
  if (typeof value === 'string') return quote(value);
  return String(value);
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

/**
 * Copies the compiled ABIs into the frontend as `as const` literals. viem infers
 * argument and return types from the ABI's literal type, so a plain JSON import
 * would erase every bit of type safety at the call site.
 *
 * Only top-level contracts are exported: interfaces and test mocks live in
 * subdirectories of artifacts/contracts and are never used by the app.
 */
async function main(): Promise<void> {
  const solDirs = readdirSync(ARTIFACTS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && entry.name.endsWith('.sol'))
    .map((entry) => entry.name)
    .sort();

  const exported: string[] = [];
  mkdirSync(OUTPUT_DIR, { recursive: true });

  for (const solDir of solDirs) {
    const dir = path.join(ARTIFACTS_DIR, solDir);
    const artifacts = readdirSync(dir).filter(
      (file) => file.endsWith('.json') && !file.endsWith('.dbg.json'),
    );

    for (const file of artifacts) {
      const artifact = JSON.parse(readFileSync(path.join(dir, file), 'utf8')) as {
        contractName: string;
        abi: unknown[];
      };
      const name = artifact.contractName;
      const constName = `${name.charAt(0).toLowerCase()}${name.slice(1)}Abi`;

      writeFileSync(
        path.join(OUTPUT_DIR, `${name}.ts`),
        `${BANNER}\n\nexport const ${constName} = ${toLiteral(artifact.abi, 0)} as const;\n`,
      );

      exported.push(name);
      console.log(`  ${name} → src/config/abis/${name}.ts (${constName})`);
    }
  }

  if (exported.length === 0) {
    throw new Error(`no artifacts found in ${ARTIFACTS_DIR} — run "npm run compile" first`);
  }

  exported.sort();
  const barrel = exported
    .map(
      (name) => `export { ${name.charAt(0).toLowerCase()}${name.slice(1)}Abi } from './${name}';`,
    )
    .join('\n');
  writeFileSync(path.join(OUTPUT_DIR, 'index.ts'), `${BANNER}\n\n${barrel}\n`);

  console.log(`Wrote ${exported.length} ABIs and an index barrel to ${OUTPUT_DIR}`);
}

run(main);
