// Generated by contracts/scripts/sync-abis.ts — run `npm run sync-abis` after changing a contract.

export const computeMarketplaceAbi = [
  {
    inputs: [
      {
        internalType: 'address',
        name: 'registry_',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'oracle_',
        type: 'address',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [
      {
        internalType: 'uint16',
        name: 'bps',
        type: 'uint16',
      },
    ],
    name: 'ConfidenceOutOfRange',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint16',
        name: 'bps',
        type: 'uint16',
      },
    ],
    name: 'FeeTooHigh',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'required',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'provided',
        type: 'uint256',
      },
    ],
    name: 'InsufficientPayment',
    type: 'error',
  },
  {
    inputs: [],
    name: 'InvalidDuration',
    type: 'error',
  },
  {
    inputs: [],
    name: 'JobNotActive',
    type: 'error',
  },
  {
    inputs: [],
    name: 'JobNotExtendable',
    type: 'error',
  },
  {
    inputs: [],
    name: 'JobNotPending',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'settleableAt',
        type: 'uint256',
      },
    ],
    name: 'LeaseNotExpired',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint16',
        name: 'confidence',
        type: 'uint16',
      },
      {
        internalType: 'uint16',
        name: 'required',
        type: 'uint16',
      },
    ],
    name: 'LowConfidence',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NodeNotActive',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NodeNotVerified',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NotConsumer',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NotProvider',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NothingToWithdraw',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
    ],
    name: 'OwnableInvalidOwner',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ReentrancyGuardReentrantCall',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'updatedAt',
        type: 'uint64',
      },
    ],
    name: 'StalePrice',
    type: 'error',
  },
  {
    inputs: [],
    name: 'WithdrawFailed',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ZeroAddress',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'from',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'Funded',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint16',
        name: 'bps',
        type: 'uint16',
      },
    ],
    name: 'IndexFeeBpsSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'fund',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'IndexFeeRouted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'fund',
        type: 'address',
      },
    ],
    name: 'IndexFundSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'provider',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'startedAt',
        type: 'uint64',
      },
    ],
    name: 'JobAccepted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'refund',
        type: 'uint256',
      },
    ],
    name: 'JobCancelled',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'completedAt',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'totalCost',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'refund',
        type: 'uint256',
      },
    ],
    name: 'JobCompleted',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'consumer',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'jobType',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'durationHours',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'pricePerHourWei',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'paymentAmount',
        type: 'uint256',
      },
    ],
    name: 'JobCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'extraHours',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'durationHours',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'paymentAmount',
        type: 'uint256',
      },
    ],
    name: 'JobExtended',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'settler',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'totalCost',
        type: 'uint256',
      },
    ],
    name: 'JobSettledLate',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint16',
        name: 'bps',
        type: 'uint16',
      },
    ],
    name: 'MinConfidenceBpsSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'payee',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'PaymentDeferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'payee',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    name: 'PendingWithdrawn',
    type: 'event',
  },
  {
    inputs: [],
    name: 'MAX_DURATION_HOURS',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_INDEX_FEE_BPS',
    outputs: [
      {
        internalType: 'uint16',
        name: '',
        type: 'uint16',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'MAX_PRICE_AGE',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'SETTLE_GRACE',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
    ],
    name: 'acceptJob',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
    ],
    name: 'cancelJob',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
    ],
    name: 'completeJob',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        internalType: 'string',
        name: 'jobType',
        type: 'string',
      },
      {
        internalType: 'string',
        name: 'specHash',
        type: 'string',
      },
      {
        internalType: 'uint64',
        name: 'durationHours',
        type: 'uint64',
      },
    ],
    name: 'createJob',
    outputs: [
      {
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
    ],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
      {
        internalType: 'uint64',
        name: 'extraHours',
        type: 'uint64',
      },
    ],
    name: 'extendJob',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
    ],
    name: 'getJob',
    outputs: [
      {
        components: [
          {
            internalType: 'uint64',
            name: 'nodeId',
            type: 'uint64',
          },
          {
            internalType: 'address',
            name: 'consumer',
            type: 'address',
          },
          {
            internalType: 'address',
            name: 'provider',
            type: 'address',
          },
          {
            internalType: 'string',
            name: 'jobType',
            type: 'string',
          },
          {
            internalType: 'string',
            name: 'specHash',
            type: 'string',
          },
          {
            internalType: 'uint256',
            name: 'pricePerHourWei',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'paymentAmount',
            type: 'uint256',
          },
          {
            internalType: 'uint64',
            name: 'durationHours',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'startedAt',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'completedAt',
            type: 'uint64',
          },
          {
            internalType: 'enum ComputeMarketplace.JobStatus',
            name: 'status',
            type: 'uint8',
          },
        ],
        internalType: 'struct ComputeMarketplace.ComputeJob',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
    ],
    name: 'getJobCost',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'indexFeeBps',
    outputs: [
      {
        internalType: 'uint16',
        name: '',
        type: 'uint16',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'indexFund',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    name: 'jobs',
    outputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        internalType: 'address',
        name: 'consumer',
        type: 'address',
      },
      {
        internalType: 'address',
        name: 'provider',
        type: 'address',
      },
      {
        internalType: 'string',
        name: 'jobType',
        type: 'string',
      },
      {
        internalType: 'string',
        name: 'specHash',
        type: 'string',
      },
      {
        internalType: 'uint256',
        name: 'pricePerHourWei',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'paymentAmount',
        type: 'uint256',
      },
      {
        internalType: 'uint64',
        name: 'durationHours',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'startedAt',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'completedAt',
        type: 'uint64',
      },
      {
        internalType: 'enum ComputeMarketplace.JobStatus',
        name: 'status',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'minConfidenceBps',
    outputs: [
      {
        internalType: 'uint16',
        name: '',
        type: 'uint16',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nextJobId',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'oracle',
    outputs: [
      {
        internalType: 'contract IPriceOracle',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    name: 'pendingWithdrawals',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'registry',
    outputs: [
      {
        internalType: 'contract IComputeRegistry',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint16',
        name: 'bps',
        type: 'uint16',
      },
    ],
    name: 'setIndexFeeBps',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'fund',
        type: 'address',
      },
    ],
    name: 'setIndexFund',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint16',
        name: 'bps',
        type: 'uint16',
      },
    ],
    name: 'setMinConfidenceBps',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
    ],
    name: 'settleExpiredJob',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'jobId',
        type: 'uint256',
      },
    ],
    name: 'settleableAt',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalJobs',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalVolumeWei',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'withdrawPending',
    outputs: [
      {
        internalType: 'uint256',
        name: 'amount',
        type: 'uint256',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    stateMutability: 'payable',
    type: 'receive',
  },
] as const;
