// Generated by contracts/scripts/sync-abis.ts — run `npm run sync-abis` after changing a contract.

export const computeRegistryAbi = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [],
    name: 'ModelRequired',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
    ],
    name: 'NodeAlreadyExists',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
    ],
    name: 'NodeNotFound',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NotMarketplace',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
    ],
    name: 'NotNodeProvider',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NotVerifier',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
    ],
    name: 'OwnableInvalidOwner',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ZeroAddress',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'marketplace',
        type: 'address',
      },
    ],
    name: 'MarketplaceSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint64',
        name: 'timestamp',
        type: 'uint64',
      },
    ],
    name: 'NodeHeartbeat',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'provider',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'model',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'string',
        name: 'region',
        type: 'string',
      },
    ],
    name: 'NodeRegistered',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'enum IComputeRegistry.NodeStatus',
        name: 'newStatus',
        type: 'uint8',
      },
    ],
    name: 'NodeStatusUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'verifier',
        type: 'address',
      },
    ],
    name: 'NodeUnverified',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'verifier',
        type: 'address',
      },
    ],
    name: 'NodeVerified',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        indexed: false,
        internalType: 'uint96',
        name: 'newTotal',
        type: 'uint96',
      },
    ],
    name: 'RevenueUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'verifier',
        type: 'address',
      },
    ],
    name: 'VerifierSet',
    type: 'event',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        internalType: 'uint96',
        name: 'amount',
        type: 'uint96',
      },
    ],
    name: 'addRevenue',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
    ],
    name: 'getNode',
    outputs: [
      {
        components: [
          {
            internalType: 'address',
            name: 'provider',
            type: 'address',
          },
          {
            components: [
              {
                internalType: 'string',
                name: 'model',
                type: 'string',
              },
              {
                internalType: 'uint16',
                name: 'vramGB',
                type: 'uint16',
              },
              {
                internalType: 'uint16',
                name: 'tflops',
                type: 'uint16',
              },
              {
                internalType: 'string',
                name: 'region',
                type: 'string',
              },
            ],
            internalType: 'struct IComputeRegistry.GpuSpecs',
            name: 'specs',
            type: 'tuple',
          },
          {
            internalType: 'enum IComputeRegistry.NodeStatus',
            name: 'status',
            type: 'uint8',
          },
          {
            internalType: 'uint96',
            name: 'totalRevenue',
            type: 'uint96',
          },
          {
            internalType: 'uint64',
            name: 'registeredAt',
            type: 'uint64',
          },
          {
            internalType: 'uint64',
            name: 'lastHeartbeat',
            type: 'uint64',
          },
          {
            internalType: 'bool',
            name: 'verified',
            type: 'bool',
          },
        ],
        internalType: 'struct IComputeRegistry.ComputeNode',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'provider',
        type: 'address',
      },
    ],
    name: 'getProviderNodes',
    outputs: [
      {
        internalType: 'uint64[]',
        name: '',
        type: 'uint64[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'provider',
        type: 'address',
      },
    ],
    name: 'getProviderRevenue',
    outputs: [
      {
        internalType: 'uint96',
        name: 'total',
        type: 'uint96',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
    ],
    name: 'heartbeat',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'marketplace',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nodeCount',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    name: 'nodes',
    outputs: [
      {
        internalType: 'address',
        name: 'provider',
        type: 'address',
      },
      {
        components: [
          {
            internalType: 'string',
            name: 'model',
            type: 'string',
          },
          {
            internalType: 'uint16',
            name: 'vramGB',
            type: 'uint16',
          },
          {
            internalType: 'uint16',
            name: 'tflops',
            type: 'uint16',
          },
          {
            internalType: 'string',
            name: 'region',
            type: 'string',
          },
        ],
        internalType: 'struct IComputeRegistry.GpuSpecs',
        name: 'specs',
        type: 'tuple',
      },
      {
        internalType: 'enum IComputeRegistry.NodeStatus',
        name: 'status',
        type: 'uint8',
      },
      {
        internalType: 'uint96',
        name: 'totalRevenue',
        type: 'uint96',
      },
      {
        internalType: 'uint64',
        name: 'registeredAt',
        type: 'uint64',
      },
      {
        internalType: 'uint64',
        name: 'lastHeartbeat',
        type: 'uint64',
      },
      {
        internalType: 'bool',
        name: 'verified',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    name: 'providerNodes',
    outputs: [
      {
        internalType: 'uint64',
        name: '',
        type: 'uint64',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: 'model',
        type: 'string',
      },
      {
        internalType: 'uint16',
        name: 'vramGB',
        type: 'uint16',
      },
      {
        internalType: 'uint16',
        name: 'tflops',
        type: 'uint16',
      },
      {
        internalType: 'string',
        name: 'region',
        type: 'string',
      },
    ],
    name: 'registerNode',
    outputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newMarketplace',
        type: 'address',
      },
    ],
    name: 'setMarketplace',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newVerifier',
        type: 'address',
      },
    ],
    name: 'setVerifier',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalActiveNodes',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
    ],
    name: 'unverifyNode',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
      {
        internalType: 'enum IComputeRegistry.NodeStatus',
        name: 'newStatus',
        type: 'uint8',
      },
    ],
    name: 'updateStatus',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'verifier',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint64',
        name: 'nodeId',
        type: 'uint64',
      },
    ],
    name: 'verifyNode',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
