// Generated by contracts/scripts/sync-abis.ts — run `npm run sync-abis` after changing a contract.

export const priceOracleAbi = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'pricePerHourWei',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'maxPriceWei',
        type: 'uint256',
      },
    ],
    name: 'AboveMaxPrice',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ArrayLengthMismatch',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'pricePerHourWei',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'floorPriceWei',
        type: 'uint256',
      },
    ],
    name: 'BelowFloorPrice',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint16',
        name: 'confidence',
        type: 'uint16',
      },
    ],
    name: 'ConfidenceOutOfRange',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'floorPriceWei',
        type: 'uint256',
      },
      {
        internalType: 'uint256',
        name: 'maxPriceWei',
        type: 'uint256',
      },
    ],
    name: 'InvalidPriceBounds',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NoPriceForModel',
    type: 'error',
  },
  {
    inputs: [],
    name: 'NotOperator',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
    ],
    name: 'OwnableInvalidOwner',
    type: 'error',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'OwnableUnauthorizedAccount',
    type: 'error',
  },
  {
    inputs: [],
    name: 'UnsupportedModel',
    type: 'error',
  },
  {
    inputs: [],
    name: 'ZeroAddress',
    type: 'error',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'string',
        name: 'model',
        type: 'string',
      },
      {
        indexed: false,
        internalType: 'uint16',
        name: 'basePriceBps',
        type: 'uint16',
      },
    ],
    name: 'BenchmarkSet',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newFloorWei',
        type: 'uint256',
      },
    ],
    name: 'FloorPriceUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: 'newMaxWei',
        type: 'uint256',
      },
    ],
    name: 'MaxPriceUpdated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'newOperator',
        type: 'address',
      },
    ],
    name: 'OperatorChanged',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'bytes32',
        name: 'modelHash',
        type: 'bytes32',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: 'pricePerHourWei',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint16',
        name: 'confidence',
        type: 'uint16',
      },
    ],
    name: 'PriceUpdated',
    type: 'event',
  },
  {
    inputs: [],
    name: 'aiOperator',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string[]',
        name: 'models',
        type: 'string[]',
      },
      {
        internalType: 'uint256[]',
        name: 'pricePerHourWeis',
        type: 'uint256[]',
      },
      {
        internalType: 'uint16[]',
        name: 'confidences',
        type: 'uint16[]',
      },
    ],
    name: 'batchUpdatePrices',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    name: 'benchmarks',
    outputs: [
      {
        internalType: 'string',
        name: 'model',
        type: 'string',
      },
      {
        internalType: 'uint16',
        name: 'basePriceBps',
        type: 'uint16',
      },
      {
        internalType: 'bool',
        name: 'supported',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'floorPriceWei',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: 'model',
        type: 'string',
      },
    ],
    name: 'getPrice',
    outputs: [
      {
        internalType: 'uint256',
        name: 'pricePerHourWei',
        type: 'uint256',
      },
      {
        internalType: 'uint64',
        name: 'updatedAt',
        type: 'uint64',
      },
      {
        internalType: 'uint16',
        name: 'confidence',
        type: 'uint16',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: 'hash',
        type: 'bytes32',
      },
    ],
    name: 'getPriceByHash',
    outputs: [
      {
        internalType: 'uint256',
        name: 'pricePerHourWei',
        type: 'uint256',
      },
      {
        internalType: 'uint64',
        name: 'updatedAt',
        type: 'uint64',
      },
      {
        internalType: 'uint16',
        name: 'confidence',
        type: 'uint16',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: 'model',
        type: 'string',
      },
    ],
    name: 'isSupported',
    outputs: [
      {
        internalType: 'bool',
        name: '',
        type: 'bool',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'maxPriceWei',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [
      {
        internalType: 'address',
        name: '',
        type: 'address',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'bytes32',
        name: '',
        type: 'bytes32',
      },
    ],
    name: 'prices',
    outputs: [
      {
        internalType: 'uint256',
        name: 'pricePerHourWei',
        type: 'uint256',
      },
      {
        internalType: 'uint64',
        name: 'updatedAt',
        type: 'uint64',
      },
      {
        internalType: 'uint16',
        name: 'confidence',
        type: 'uint16',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: 'model',
        type: 'string',
      },
      {
        internalType: 'uint16',
        name: 'basePriceBps',
        type: 'uint16',
      },
    ],
    name: 'setBenchmark',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'floorWei',
        type: 'uint256',
      },
    ],
    name: 'setFloorPrice',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'maxWei',
        type: 'uint256',
      },
    ],
    name: 'setMaxPrice',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newOperator',
        type: 'address',
      },
    ],
    name: 'setOperator',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'string',
        name: 'model',
        type: 'string',
      },
      {
        internalType: 'uint256',
        name: 'pricePerHourWei',
        type: 'uint256',
      },
      {
        internalType: 'uint16',
        name: 'confidence',
        type: 'uint16',
      },
    ],
    name: 'updatePrice',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
